<!DOCTYPE html>
<html>
<head>
	<title>daftarproker.pdf</title>
	<style type="text/css">
		@page  { 
			margin: 0.5in 0.5in;
        }
        body{
        	margin:30px;
        	line-height: 0.6;
        	font-size:12px;
        }
        .wide-spacing1{
        	line-height: 1.5;
        }
        .wide-spacing2{
        	line-height: 1.0;
        }

        table{
        	width: 100%;
        	border: 1pt solid black;
        	border-collapse: collapse;
        	font-size:12px;
        }

        td,th{
        	padding: 10px;
        	border: 1px solid;
        }

        footer { position: fixed; bottom: -60px; left: 0px; right: 0px; height: 50px; }
	</style>
</head>
	<body>
		<div id="header">
			<p style="text-align:center;">PEMERINTAH PROVINSI JAWA TENGAH</p>
			<p style="text-align:center;">DINAS PENDIDIKAN</p>
			<p style="text-align:center;font-size:20px;"><strong>SMA NEGERI PERCONTOHAN</strong></p>
			<p style="text-align:center;">Jalan Srikaya 26 Surakarta, Jawa Tengah (0271) 5534454</p>
			<hr>
		</div>
		<div id="container">
			<p class="wide-spacing1" style="text-align:center;font-size:20px;text-transform:uppercase;"><strong>Daftar Program Kerja Ekstrakurikuler <?php echo e($name); ?><strong></p>
			<table class="wide-spacing2">
				<tr>
        			<th>No</th>
        			<th>Nama Program Kerja</th>
        			<th>Deskripsi</th>
                    <th>Tanggal</th>
        			<th>Tempat Penyelenggaraan</th>
        			<th>Target</th>
        			<th>Rencana Anggaran</th>
        		</tr>
                <?php $i = 0 ?>
                <?php $__currentLoopData = $proker; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $proker): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                <?php $i++ ?>
        		<tr>
        			<td><?php echo e($i); ?></td>
        			<td><?php echo e($proker->nama_proker); ?></td>
                    <td><?php echo e($proker->deskripsi_proker); ?></td>
                    <td><?php echo e($proker->waktu_proker); ?></td>
        			<td><?php echo e($proker->tempat_proker); ?></td>
        			<td><?php echo e($proker->target_proker); ?></td>
                    <td>Rp. <?php echo e($proker->anggaran_proker); ?></td>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        		</tr>
			</table>
		</div>

		<div id="signature">
			<table style="border:0;" class="wide-spacing2">
				<tr>
					<td style="border:0;width:50%;">
						<br><br>
						<p style="text-align:center;">Pembina Ekstrakurikuler,</p>
						<br><br><br><br><br><br>
						<?php $__currentLoopData = $pembina; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $pembina): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
						<p style="text-align:center;"><?php echo e($pembina->nama_pembina); ?></p>
						<p style="text-align:center;">NIP. <?php echo e($pembina->nip_pembina); ?></p>
						<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
					</td>
					<td style="border:0;width:50%;">
						<p style="text-align:center;">Surakarta, <?php echo e($tanggal); ?></p>
						<p style="text-align:center;">Ketua Ekstrakurikuler<br><?php echo e($name); ?>,</p>
						<br><br><br><br><br><br>
						<?php $__currentLoopData = $ketua; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $ketua): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
						<p style="text-align:center;"><?php echo e($ketua->nama_siswa); ?></p>
						<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
					</td>
				</tr>
			</table>
		</div>

		<footer>
		<p style="font-size:8px;font-family:'Courier', sans-serif;">Generated by Simekskul. <?php echo e(\Carbon\Carbon::now()); ?> + 7h (Western Indonesian Time)</p>
		</footer>
	</body>
</html>